import { Search } from "../src/components/Search";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className="bg-black text-white">
      <body className="p-4">
        <div className="pb-4">
          <Search />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
